name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install
    - run: npm test
    - run: uname -a
    - run: apt-get update || sudo !!
    - run: apt-get install -y neofetch || sudo !!
    - run: neofetch
